# Generated by Django 5.2.7 on 2025-10-29 05:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_usertoken'),
    ]

    operations = [
        migrations.AddField(
            model_name='exam',
            name='rubrics',
            field=models.TextField(blank=True, null=True),
        ),
    ]
