# Generated by Django 5.2.7 on 2025-10-30 06:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0007_documentchunk'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='studentexamsubmission',
            unique_together=set(),
        ),
        migrations.AddField(
            model_name='studentexamsubmission',
            name='is_submitted',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='studentexamsubmission',
            name='responses',
            field=models.JSONField(default='{}'),
        ),
        migrations.RemoveField(
            model_name='studentexamsubmission',
            name='overall_feedback',
        ),
        migrations.RemoveField(
            model_name='studentexamsubmission',
            name='overall_received_score',
        ),
    ]
