# Generated by Django 5.2.7 on 2025-10-30 07:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0008_alter_studentexamsubmission_unique_together_and_more'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='studentexamsubmission',
            unique_together={('student', 'exam')},
        ),
        migrations.AddField(
            model_name='studentexamsubmission',
            name='overall_feedback',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='studentexamsubmission',
            name='overall_received_score',
            field=models.FloatField(default=0.0),
        ),
        migrations.RemoveField(
            model_name='studentexamsubmission',
            name='is_submitted',
        ),
        migrations.RemoveField(
            model_name='studentexamsubmission',
            name='responses',
        ),
    ]
